### ISSUE TITLE
Can't transfer net to CUDA Device

### ISSUE THREAD

**Issue by Erik-Sovereign** [microsoft/WSL2-Linux-Kernel#128]
Windows Version: Version 2004 (Build 20150.1000)
Linux Kernel: 4.19.121-microsoft-WSL2-standard
Geforce Version: 455.41
PyTorch Version: 1.2
Python Version: 3.5.4

I want to switch from my Ubuntu 18.04 Dual Boot to WSL 2 Ubuntu 20.04.
I tested my PyTorch CNN Training Script in WSL. 
It recognized my Nvidia GPU. 
(torch.cuda.is_available() gave true and 
torch.cuda.get_device_name(device) gave "GeForce RTX 2070 SUPER")

It downloaded ResNet but when I wanted to move the net to the GPU with 
`net.to(device) `
the following error occured and the script crashed:
```
Traceback (most recent call last):
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/erik/.vscode-server/extensions/ms-python.python-2020.6.89148/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/local/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erik/XXX/surgical_phase_recognition/Train_SurgicalPhaseRecognition.py", line 77, in <module>
    net.to(device)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
```

This didn't happen in my Ubuntu Dual Boot.

Thanks :)

**Comment by Erik-Sovereign** [comment]
I will post it to https://github.com/microsoft/WSL
